
export const GET_RANDOM_NUMBER = 'GET_RANDOM_NUMBER';
export const GET_RANDOM_NUMBER_SUCCESS = 'GET_RANDOM_NUMBER_SUCCESS';
export const GET_RANDOM_NUMBER_FALIURE = 'GET_RANDOM_NUMBER_FALIURE';
export const FETCH_AMENITIES = 'FETCH_AMENITIES';
export const FETCH_AMENITIES_SUCCESS = 'FETCH_AMENITIES_SUCCESS';
export const FETCH_AMENITIES_FAILIURE = 'FETCH_AMENITIES_FAILIURE';